PORTNAME=	guru
DISTVERSION=	1.0
CATEGORIES=	sysutils
MASTER_SITES=	ftp://ftp.rediris.es/sites/ftp.freebsd.org/pub/FreeBSD/

MAINTAINER=	wb7odyfred@yahoo.com
COMMENT=	Generate User Report for Upload,  GURU, gzip Report for compressed size
WWW=		http://github.com/wb7odyfred/Ghostbsd_apps

USE_GITHUB= yes
GH_ACCOUNT= wb7odyfred
GH_PROJECT= guru
WRKSRC_SUBDIR=$(PORTNAME}

    do-build:
      cd ${WRKSRC} && ${MAKE}

    do-install:
      ${INSTALL_PROGRAM} ${WRKSRC}/bin/* ${STAGEDIR}${PREFIX}/bin/


#  .include <bsd.port.mk>

[section to describe the port itself and the master site - PORTNAME
 and PORTVERSION or the DISTVERSION* variables are always first,
 followed by CATEGORIES, and then MASTER_SITES, which can be followed
 by MASTER_SITE_SUBDIR.  PKGNAMEPREFIX and PKGNAMESUFFIX, if needed,
 will be after that.  Then comes DISTNAME, EXTRACT_SUFX and/or
 DISTFILES, and then EXTRACT_ONLY, as necessary.]
[do not forget the trailing slash ("/")!
 if not using MASTER_SITE_* macros]
# MASTER_SITES=	${MASTER_SITE_XCONTRIB}
# MASTER_SITE_SUBDIR=	applications
# PKGNAMEPREFIX=	ja-
# DISTNAME=	xdvi-pl18
[set this if the source is not in the standard ".tar.gz" form]
# EXTRACT_SUFX=	.tar.Z

[section for distributed patches -- can be empty]
# PATCH_SITES=	ftp://ftp.sra.co.jp/pub/X11/japanese/
# PATCHFILES=	xdvi-18.patch1.gz xdvi-18.patch2.gz
[If the distributed patches were not made relative to ${WRKSRC},
 this may need to be tweaked]
# PATCH_DIST_STRIP=	-p1

[maintainer; *mandatory*!  This is the person who is volunteering to
 handle port updates, build breakages, and to whom a users can direct
 questions and bug reports.  To keep the quality of the Ports Collection
 as high as possible, we do not accept new ports that are assigned to
 "ports@FreeBSD.org".]
# MAINTAINER=	asami@FreeBSD.org
# COMMENT=	DVI Previewer for the X Window System
# WWW=		http://xdvi.sourceforge.net/

[license -- should not be empty]
LICENSE=	BSD2CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

[dependencies -- can be empty]
# RUN_DEPENDS=	gs:print/ghostscript

[If it requires GNU make, not /usr/bin/make, to build...]
# USES= gmake
[If it is an X application and requires "xmkmf -a" to be run...]
# USES= imake

[this section is for other standard bsd.port.mk variables that do not]
 belong to any of the above]
[If it asks questions during configure, build, install...]
# IS_INTERACTIVE=	yes
[If it extracts to a directory other than ${DISTNAME}...]
# WRKSRC=		${WRKDIR}/xdvi-new
[If it requires a "configure" script generated by GNU autoconf to be run]
# GNU_CONFIGURE=	yes
[et cetera.]

[If it requires options, this section is for options]
# OPTIONS_DEFINE=	DOCS EXAMPLES FOO
# OPTIONS_DEFAULT=	FOO
[If options will change the files in plist]
# OPTIONS_SUB=yes

# FOO_DESC=		Enable foo support

# FOO_CONFIGURE_ENABLE=	foo

[non-standard variables to be used in the rules below]
# MY_FAVORITE_RESPONSE=	"yeah, right"

[then the special rules, in the order they are called]
pre-fetch:
# 	i go fetch something, yeah

post-patch:
# 	i need to do something after patch, great

pre-install:
# 	and then some more stuff before installing, wow

[and then the epilogue]
PLIST_FILES= applets-screenshooter.png
~/Desktop/Generate_User_Report.desktop		
Makefile				
pkg-descr
pkg-message
README.md				
~/Desktop/report_fred-ghostbsd-pc1_2020-04-05.txt
User_Report.py
User_Report.sh


.include <bsd.port.mk>

